name: firstworkflow

on:
  issues:
    types:
      - closed

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: bertrand
        run: echo "Hi guys, we are learning GitHub Actions"
      - name: Install Apache
        run: sudo apt-get install apache2 -y

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        run: sudo apt-get install openjdk-11-jdk -y
